/**
 * Display-only time arithmetic for the timer UI (§5.3).
 *
 * **Nothing here ever produces a value that is sent anywhere.** The saved
 * duration is `duration_seconds`, generated by Postgres from two `now()`
 * timestamps it chose itself; the numbers below exist so a person can watch a
 * counter move. That is why every function takes `now` as an argument rather
 * than reading the clock itself: a pure function is testable, and a function
 * that cannot reach `Date.now()` cannot accidentally become the source of a
 * stored value.
 */

/**
 * The stale threshold used when the company's own `max_timer_hours` is not
 * available to this layer.
 *
 * **This is a gap, not a setting.** `companies.max_timer_hours` (§3.1, §5.4)
 * exists in the database and defaults to 12, but `getCurrentMember()` returns
 * `{ id, name, timezone }` for the company and nothing else, and this layer may
 * not write the query that would widen it. A company that chose 8 or 24 at
 * onboarding is therefore judged against 12 here until the field is added to
 * `CurrentMember` — the number below is the database default, which makes it
 * right for every company that left the setting alone and wrong for any that
 * did not.
 */
export const DEFAULT_MAX_TIMER_HOURS = 12;

const SECONDS_PER_HOUR = 3600;

/**
 * Seconds between the server's `started_at` and the client's idea of now.
 *
 * Clamped at zero because the two clocks are not the same clock (§5.3): a
 * browser running a few seconds behind the database would otherwise render a
 * negative counter for its first ticks. Clamping distorts only the display,
 * which is the only thing this value feeds.
 */
export function elapsedSeconds(startedAt: string, now: number): number {
  const started = Date.parse(startedAt);
  if (Number.isNaN(started)) {
    return 0;
  }

  return Math.max(0, Math.floor((now - started) / 1000));
}

/**
 * `H:MM:SS`, growing past 24 hours rather than wrapping — a 26-hour stale timer
 * reads `26:00:00`, not `02:00:00`. Wrapping would make the one state the user
 * most needs to notice (§5.4) look ordinary.
 */
export function formatClock(seconds: number): string {
  const total = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(total / SECONDS_PER_HOUR);
  const minutes = Math.floor((total % SECONDS_PER_HOUR) / 60);
  const secs = total % 60;

  return `${hours}:${String(minutes).padStart(2, "0")}:${String(secs).padStart(2, "0")}`;
}

/** Whole hours, for prose: "Your timer has been running 19 hours" (§5.4). */
export function formatApproxHours(seconds: number): string {
  const hours = Math.floor(Math.max(0, seconds) / SECONDS_PER_HOUR);
  if (hours < 1) {
    const minutes = Math.floor(Math.max(0, seconds) / 60);
    return `${minutes} minute${minutes === 1 ? "" : "s"}`;
  }

  return `${hours} hour${hours === 1 ? "" : "s"}`;
}

/**
 * §5.4 — "a timer running longer than `companies.max_timer_hours` is stale."
 *
 * Stale is a question the UI asks, never a state the database writes: there is
 * no `stale` column and no job that closes anything. This returning true
 * changes what is rendered and nothing else.
 */
export function isStale(elapsed: number, maxTimerHours: number): boolean {
  return elapsed > maxTimerHours * SECONDS_PER_HOUR;
}
